# Generated by Django 4.2.7 on 2025-06-19 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Comment text', verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comment (not visible to clients)', verbose_name='Is internal')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('leak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leaks.leak', verbose_name='Leak')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment', verbose_name='Parent comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='comment_attachments/%Y/%m/%d/', verbose_name='File')),
                ('filename', models.CharField(max_length=255, verbose_name='Filename')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes', verbose_name='File size')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='comments.comment', verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Comment Attachment',
                'verbose_name_plural': 'Comment Attachments',
                'db_table': 'comment_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['leak'], name='comments_leak_id_401788_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='comments_author__25752a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='comments_created_d5740c_idx'),
        ),
    ]
